-- ─────────────────────────────────────────────────────────────────────────────
-- CLIENT MEETINGS MODULE — Schema Migration
-- Run this in your Supabase SQL editor (Dashboard → SQL Editor → New query)
--
-- 100% NON-DESTRUCTIVE:
--   • No existing columns dropped or modified
--   • All new columns are nullable with safe defaults
--   • All existing rows are preserved
--   • Backfill sets sensible values from existing data
-- ─────────────────────────────────────────────────────────────────────────────

-- ─── 1. Add new columns to public.meetings ──────────────────────────────────

ALTER TABLE public.meetings
  ADD COLUMN IF NOT EXISTS status               TEXT    DEFAULT 'Scheduled',
  ADD COLUMN IF NOT EXISTS outcome              TEXT,
  ADD COLUMN IF NOT EXISTS outcome_notes        TEXT,
  ADD COLUMN IF NOT EXISTS location             TEXT,
  ADD COLUMN IF NOT EXISTS meeting_link         TEXT,
  ADD COLUMN IF NOT EXISTS attendees            TEXT,
  ADD COLUMN IF NOT EXISTS follow_up_date       TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS follow_up_notes      TEXT,
  ADD COLUMN IF NOT EXISTS is_cancelled         BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS cancellation_reason  TEXT,
  ADD COLUMN IF NOT EXISTS conversion_score_delta INTEGER DEFAULT 0;

-- ─── 2. Backfill status from existing data ───────────────────────────────────
-- Rows whose end_date has passed → mark as "Completed"
-- Rows in the future → keep as "Scheduled"

UPDATE public.meetings
SET status = CASE
  WHEN end_date < NOW() THEN 'Completed'
  ELSE 'Scheduled'
END
WHERE status IS NULL OR status = '';

-- ─── 3. Ensure is_cancelled defaults correctly for old rows ─────────────────

UPDATE public.meetings
SET is_cancelled = FALSE
WHERE is_cancelled IS NULL;

-- ─── 4. Indexes for common query patterns ───────────────────────────────────

-- Filter by agent + start date (most common query)
CREATE INDEX IF NOT EXISTS idx_meetings_referenceid_start
  ON public.meetings (referenceid, start_date DESC);

-- Filter by TSM
CREATE INDEX IF NOT EXISTS idx_meetings_tsm_start
  ON public.meetings (tsm, start_date DESC);

-- Filter by manager
CREATE INDEX IF NOT EXISTS idx_meetings_manager_start
  ON public.meetings (manager, start_date DESC);

-- Filter by status
CREATE INDEX IF NOT EXISTS idx_meetings_status
  ON public.meetings (status);

-- Conflict detection (overlap check)
CREATE INDEX IF NOT EXISTS idx_meetings_conflict
  ON public.meetings (referenceid, start_date, end_date)
  WHERE is_cancelled = FALSE;

-- ─── 5. Verify ───────────────────────────────────────────────────────────────
-- Run this SELECT to confirm all columns exist:
SELECT
  column_name,
  data_type,
  column_default,
  is_nullable
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name   = 'meetings'
ORDER BY ordinal_position;




create table public.meetings (
  id bigint generated by default as identity not null,
  referenceid text null,
  tsm text null,
  manager text null,
  type_activity text null,
  remarks text null,
  start_date timestamp without time zone null,
  end_date timestamp without time zone null,
  date_created date not null default (now() AT TIME ZONE 'Asia/Manila'::text),
  date_updated date null,
  company_name text null,
  constraint meetings_pkey primary key (id)
) TABLESPACE pg_default;